# syntax=docker/dockerfile:1

ARG NEXTCLOUD_VERSION=24.0.7
ARG ALPINE_VERSION=3.16
ARG SMBCLIENT_VERSION=1.0.6

FROM crazymax/yasu:latest AS yasu
FROM --platform=${BUILDPLATFORM:-linux/amd64} crazymax/alpine-s6:${ALPINE_VERSION}-2.2.0.3 AS download
RUN apk --update --no-cache add curl gnupg tar unzip xz

ARG NEXTCLOUD_VERSION
WORKDIR /tmp
RUN curl -SsOL "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" \
  && curl -SsOL "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc" \
  && curl -SsOL "https://nextcloud.com/nextcloud.asc"
RUN gpg --import "nextcloud.asc" \
  && gpg --verify --batch --no-tty "nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc" "nextcloud-${NEXTCLOUD_VERSION}.tar.bz2"
WORKDIR /dist/nextcloud
RUN tar -xjf "/tmp/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" --strip 1 -C .

FROM crazymax/alpine-s6:${ALPINE_VERSION}-2.2.0.3

ARG SMBCLIENT_VERSION
RUN apk --update --no-cache add \
    bash \
    ca-certificates \
    curl \
    ffmpeg \
    imagemagick \
    ghostscript \
    libsmbclient \
    libxml2 \
    nginx \
    openssl \
    php8 \
    php8-bcmath \
    php8-bz2 \
    php8-cli \
    php8-ctype \
    php8-curl \
    php8-dom \
    php8-exif \
    php8-fileinfo \
    php8-fpm \
    php8-ftp \
    php8-gd \
    php8-gmp \
    php8-iconv \
    php8-intl \
    php8-json \
    php8-ldap \
    php8-mbstring \
    php8-opcache \
    php8-openssl \
    php8-pcntl \
    php8-pecl-apcu \
    php8-pecl-imagick \
    php8-pecl-mcrypt \
    php8-pecl-memcached \
    php8-pdo \
    php8-pdo_mysql \
    php8-pdo_pgsql \
    php8-pdo_sqlite \
    php8-posix \
    php8-redis \
    php8-session \
    php8-simplexml \
    php8-sqlite3 \
    php8-xml \
    php8-xmlreader \
    php8-xmlwriter \
    php8-zip \
    php8-zlib \
    python3 \
    py3-pip \
    tzdata \
  && mv /etc/php8 /etc/php && ln -s /etc/php /etc/php8 \
  && mv /etc/init.d/php-fpm8 /etc/init.d/php-fpm && ln -s /etc/init.d/php-fpm /etc/init.d/php-fpm8 \
  && mv /etc/logrotate.d/php-fpm8 /etc/logrotate.d/php-fpm && ln -s /etc/logrotate.d/php-fpm /etc/logrotate.d/php-fpm8 \
  && mv /var/log/php8 /var/log/php && ln -s /var/log/php /var/log/php8 \
  && ln -s /usr/sbin/php-fpm8 /usr/sbin/php-fpm \
  && apk --update --no-cache add -t build-dependencies \
    autoconf \
    automake \
    build-base \
    libtool \
    pcre-dev \
    php8-dev \
    php8-pear \
    samba-dev \
    tar \
    wget \
  && pip3 install --upgrade pip \
  && pip3 install nextcloud_news_updater \
  && cd /tmp \
  && wget -q https://pecl.php.net/get/smbclient-${SMBCLIENT_VERSION}.tgz \
  && pecl8 install smbclient-${SMBCLIENT_VERSION}.tgz \
  && apk del build-dependencies \
  && rm -rf /tmp/* /var/www/*

ENV S6_BEHAVIOUR_IF_STAGE2_FAILS="2" \
  TZ="UTC" \
  PUID="1000" \
  PGID="1000"

COPY --from=yasu / /
COPY --from=download --chown=nobody:nogroup /dist/nextcloud /var/www
COPY rootfs /

RUN addgroup -g ${PGID} nextcloud \
  && adduser -D -h /home/nextcloud -u ${PUID} -G nextcloud -s /bin/sh nextcloud

EXPOSE 8000
WORKDIR /var/www
VOLUME [ "/data" ]

ENTRYPOINT [ "/init" ]

HEALTHCHECK --interval=10s --timeout=5s --start-period=20s \
  CMD /usr/local/bin/healthcheck
