ARG NEXTCLOUD_VERSION=22.2.2
ARG SMBCLIENT_VERSION=1.0.6

FROM crazymax/yasu:latest AS yasu
FROM --platform=${BUILDPLATFORM:-linux/amd64} crazymax/alpine-s6:3.14-2.2.0.3 AS download
RUN apk --update --no-cache add curl gnupg tar unzip xz

ARG NEXTCLOUD_VERSION
WORKDIR /tmp
RUN curl -SsOL "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" \
  && curl -SsOL "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc" \
  && curl -SsOL "https://nextcloud.com/nextcloud.asc"
RUN gpg --import "nextcloud.asc" \
  && gpg --verify --batch --no-tty "nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc" "nextcloud-${NEXTCLOUD_VERSION}.tar.bz2"
WORKDIR /dist/nextcloud
RUN tar -xjf "/tmp/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" --strip 1 -C .

FROM crazymax/alpine-s6:3.14-2.2.0.3

ARG SMBCLIENT_VERSION
RUN apk --update --no-cache add \
    bash \
    ca-certificates \
    curl \
    ffmpeg \
    imagemagick \
    ghostscript \
    libsmbclient \
    libxml2 \
    nginx \
    openssl \
    php7 \
    php7-bcmath \
    php7-bz2 \
    php7-cli \
    php7-ctype \
    php7-curl \
    php7-dom \
    php7-exif \
    php7-fileinfo \
    php7-fpm \
    php7-ftp \
    php7-gd \
    php7-gmp \
    php7-iconv \
    php7-intl \
    php7-json \
    php7-ldap \
    php7-mbstring \
    php7-opcache \
    php7-openssl \
    php7-pcntl \
    php7-pecl-apcu \
    php7-pecl-imagick \
    php7-pecl-mcrypt \
    php7-pecl-memcached \
    php7-pdo \
    php7-pdo_mysql \
    php7-pdo_pgsql \
    php7-pdo_sqlite \
    php7-posix \
    php7-redis \
    php7-session \
    php7-simplexml \
    php7-sqlite3 \
    php7-xml \
    php7-xmlreader \
    php7-xmlwriter \
    php7-zip \
    php7-zlib \
    python3 \
    py3-pip \
    tzdata \
  && apk --update --no-cache add -t build-dependencies \
    autoconf \
    automake \
    build-base \
    libtool \
    pcre-dev \
    php7-dev \
    php7-pear \
    samba-dev \
    tar \
    wget \
  && pip3 install --upgrade pip \
  && pip3 install nextcloud_news_updater \
  && cd /tmp \
  && wget -q https://pecl.php.net/get/smbclient-${SMBCLIENT_VERSION}.tgz \
  && pecl install smbclient-${SMBCLIENT_VERSION}.tgz \
  && apk del build-dependencies \
  && rm -rf /tmp/* /var/cache/apk/* /var/www/*

ENV S6_BEHAVIOUR_IF_STAGE2_FAILS="2" \
  TZ="UTC" \
  PUID="1000" \
  PGID="1000"

COPY --from=yasu / /
COPY --from=download --chown=nobody:nogroup /dist/nextcloud /var/www
COPY rootfs /

RUN addgroup -g ${PGID} nextcloud \
  && adduser -D -h /home/nextcloud -u ${PUID} -G nextcloud -s /bin/sh nextcloud

EXPOSE 8000
WORKDIR /var/www
VOLUME [ "/data" ]

ENTRYPOINT [ "/init" ]

HEALTHCHECK --interval=10s --timeout=5s --start-period=20s \
  CMD /usr/local/bin/healthcheck
