# syntax=docker/dockerfile:1

ARG NEXTCLOUD_VERSION=26.0.0
ARG ALPINE_VERSION=3.17
ARG SMBCLIENT_VERSION=1.0.6

FROM crazymax/yasu:latest AS yasu
FROM --platform=${BUILDPLATFORM:-linux/amd64} crazymax/alpine-s6:${ALPINE_VERSION}-2.2.0.3 AS download
RUN apk --update --no-cache add curl gnupg tar unzip xz

ARG NEXTCLOUD_VERSION
WORKDIR /tmp
RUN curl -SsOL "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" \
  && curl -SsOL "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc" \
  && curl -SsOL "https://nextcloud.com/nextcloud.asc"
RUN gpg --import "nextcloud.asc" \
  && gpg --verify --batch --no-tty "nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc" "nextcloud-${NEXTCLOUD_VERSION}.tar.bz2"
WORKDIR /dist/nextcloud
RUN tar -xjf "/tmp/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" --strip 1 -C .

FROM crazymax/alpine-s6:${ALPINE_VERSION}-2.2.0.3

ARG SMBCLIENT_VERSION
RUN apk --update --no-cache add \
    bash \
    ca-certificates \
    curl \
    ffmpeg \
    imagemagick \
    ghostscript \
    libsmbclient \
    libxml2 \
    nginx \
    openssl \
    php81 \
    php81-bcmath \
    php81-bz2 \
    php81-cli \
    php81-ctype \
    php81-curl \
    php81-dom \
    php81-exif \
    php81-fileinfo \
    php81-fpm \
    php81-ftp \
    php81-gd \
    php81-gmp \
    php81-iconv \
    php81-intl \
    php81-json \
    php81-ldap \
    php81-mbstring \
    php81-opcache \
    php81-openssl \
    php81-pcntl \
    php81-pecl-apcu \
    php81-pecl-imagick \
    php81-pecl-memcached \
    php81-pdo \
    php81-pdo_mysql \
    php81-pdo_pgsql \
    php81-pdo_sqlite \
    php81-posix \
    php81-redis \
    php81-session \
    php81-simplexml \
    php81-sqlite3 \
    php81-sysvsem \
    php81-xml \
    php81-xmlreader \
    php81-xmlwriter \
    php81-zip \
    php81-zlib \
    python3 \
    py3-pip \
    tzdata \
  && mv /etc/php81 /etc/php && ln -s /etc/php /etc/php81 \
  && mv /etc/init.d/php-fpm81 /etc/init.d/php-fpm && ln -s /etc/init.d/php-fpm /etc/init.d/php-fpm81 \
  && mv /etc/logrotate.d/php-fpm81 /etc/logrotate.d/php-fpm && ln -s /etc/logrotate.d/php-fpm /etc/logrotate.d/php-fpm81 \
  && mv /var/log/php81 /var/log/php && ln -s /var/log/php /var/log/php81 \
  && ln -s /usr/sbin/php-fpm81 /usr/sbin/php-fpm \
  && apk --update --no-cache add -t build-dependencies \
    autoconf \
    automake \
    build-base \
    libtool \
    pcre-dev \
    php81-dev \
    php81-pear \
    samba-dev \
    tar \
    wget \
  && pip3 install --upgrade pip \
  && pip3 install nextcloud_news_updater \
  && cd /tmp \
  && wget -q https://pecl.php.net/get/smbclient-${SMBCLIENT_VERSION}.tgz \
  && pecl81 install smbclient-${SMBCLIENT_VERSION}.tgz \
  && apk del build-dependencies \
  && rm -rf /tmp/* /var/www/*

ENV S6_BEHAVIOUR_IF_STAGE2_FAILS="2" \
  TZ="UTC" \
  PUID="1000" \
  PGID="1000"

COPY --from=yasu / /
COPY --from=download --chown=nobody:nogroup /dist/nextcloud /var/www
COPY rootfs /

RUN addgroup -g ${PGID} nextcloud \
  && adduser -D -h /home/nextcloud -u ${PUID} -G nextcloud -s /bin/sh nextcloud

EXPOSE 8000
WORKDIR /var/www
VOLUME [ "/data" ]

ENTRYPOINT [ "/init" ]

HEALTHCHECK --interval=10s --timeout=5s --start-period=20s \
  CMD /usr/local/bin/healthcheck
