# syntax=docker/dockerfile:1

ARG NEXTCLOUD_VERSION=29.0.2
ARG ALPINE_VERSION=3.19

FROM crazymax/yasu:latest AS yasu
FROM --platform=${BUILDPLATFORM:-linux/amd64} crazymax/alpine-s6:${ALPINE_VERSION}-2.2.0.3 AS download
RUN apk --update --no-cache add curl gnupg tar unzip xz

ARG NEXTCLOUD_VERSION
WORKDIR /tmp
RUN curl -SsOL "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" \
  && curl -SsOL "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc" \
  && curl -SsOL "https://nextcloud.com/nextcloud.asc"
RUN gpg --import "nextcloud.asc" \
  && gpg --verify --batch --no-tty "nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc" "nextcloud-${NEXTCLOUD_VERSION}.tar.bz2"
WORKDIR /dist/nextcloud
RUN tar -xjf "/tmp/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" --strip 1 -C .

FROM crazymax/alpine-s6:${ALPINE_VERSION}-2.2.0.3
RUN apk --update --no-cache add \
    bash \
    ca-certificates \
    curl \
    ffmpeg \
    util-linux \
    imagemagick \
    imagemagick-pdf \
    imagemagick-heic \
    imagemagick-svg \
    ghostscript \
    libxml2 \
    mysql-client \
    nginx \
    openssl \
    php82 \
    php82-bcmath \
    php82-bz2 \
    php82-cli \
    php82-ctype \
    php82-curl \
    php82-dom \
    php82-exif \
    php82-fileinfo \
    php82-fpm \
    php82-ftp \
    php82-gd \
    php82-gmp \
    php82-iconv \
    php82-imap \
    php82-intl \
    php82-json \
    php82-ldap \
    php82-mbstring \
    php82-opcache \
    php82-openssl \
    php82-pcntl \
    php82-pecl-apcu \
    php82-pecl-imagick \
    php82-pecl-memcached \
    php82-pecl-smbclient \
    php82-pdo \
    php82-pdo_mysql \
    php82-pdo_pgsql \
    php82-pdo_sqlite \
    php82-posix \
    php82-redis \
    php82-session \
    php82-simplexml \
    php82-sodium \
    php82-sqlite3 \
    php82-sysvsem \
    php82-xml \
    php82-xmlreader \
    php82-xmlwriter \
    php82-zip \
    php82-zlib \
    postgresql-client \
    python3 \
    py3-pip \
    tzdata \
  && mv /etc/php82 /etc/php && ln -s /etc/php /etc/php82 \
  && mv /etc/init.d/php-fpm82 /etc/init.d/php-fpm && ln -s /etc/init.d/php-fpm /etc/init.d/php-fpm82 \
  && mv /etc/logrotate.d/php-fpm82 /etc/logrotate.d/php-fpm && ln -s /etc/logrotate.d/php-fpm /etc/logrotate.d/php-fpm82 \
  && mv /var/log/php82 /var/log/php && ln -s /var/log/php /var/log/php82 \
  && ln -s /usr/sbin/php-fpm82 /usr/sbin/php-fpm \
  && pip3 install --upgrade --break-system-packages pip \
  && pip3 install --break-system-packages nextcloud_news_updater \
  && cd /tmp \
  && rm -rf /tmp/* /var/www/*

ENV S6_BEHAVIOUR_IF_STAGE2_FAILS="2" \
  TZ="UTC" \
  PUID="1000" \
  PGID="1000"

COPY --from=yasu / /
COPY --from=download --chown=nobody:nogroup /dist/nextcloud /var/www
COPY rootfs /

RUN addgroup -g ${PGID} nextcloud \
  && adduser -D -h /home/nextcloud -u ${PUID} -G nextcloud -s /bin/sh nextcloud

EXPOSE 8000
WORKDIR /var/www
VOLUME [ "/data" ]

ENTRYPOINT [ "/init" ]

HEALTHCHECK --interval=10s --timeout=5s --start-period=20s \
  CMD /usr/local/bin/healthcheck
