name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

env:
  LATEST_DOCKERFILE: v34.Dockerfile

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      dockerfile: ${{ steps.prepare.outputs.dockerfile }}
      latest: ${{ steps.prepare.outputs.latest }}
    steps:
      -
        name: Prepare
        id: prepare
        run: |
          dockerfile="${LATEST_DOCKERFILE}"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            tag="${GITHUB_REF#refs/tags/}"
            dockerfile="v${tag%%.*}.Dockerfile"
          fi
          echo "dockerfile=${dockerfile}" >> "${GITHUB_OUTPUT}"
          if [[ "${dockerfile}" == "${LATEST_DOCKERFILE}" && "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "latest=true" >> "${GITHUB_OUTPUT}"
          else
            echo "latest=false" >> "${GITHUB_OUTPUT}"
          fi

  build:
    uses: docker/github-builder/.github/workflows/bake.yml@a492c6d04fd3315f67230809b44d60cc0acd50b3 # v1.16.0
    needs:
      - prepare
    permissions:
      contents: read # same as global permissions
      id-token: write # for signing attestation(s) with GitHub OIDC Token
      packages: write # required to push to GHCR
    with:
      setup-qemu: true
      target: image-all
      cache: true
      cache-scope: build
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      set-meta-labels: true
      meta-images: |
        crazymax/nextcloud
        ghcr.io/crazy-max/nextcloud
      meta-tags: |
        type=match,pattern=(.*)-r,group=1
        type=ref,event=pr
        type=edge
      meta-flavor: |
        latest=${{ needs.prepare.outputs.latest == 'true' }}
      meta-labels: |
        org.opencontainers.image.title=Nextcloud
        org.opencontainers.image.description=Suite of client-server software for creating and using file hosting services
        org.opencontainers.image.vendor=CrazyMax
      vars: |
        DOCKERFILE=${{ needs.prepare.outputs.dockerfile }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
