name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

env:
  BUILD_TAG: nextcloud:test
  CONTAINER_NAME: nextcloud

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_file:
          - v31.Dockerfile
          - v32.Dockerfile
          - v33.Dockerfile
        dir:
          - mysql
          - pgsql
          - sqlite
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      -
        name: Build
        uses: docker/bake-action@82490499d2e5613fcead7e128237ef0b0ea210f7 # v7.0.0
        with:
          source: .
          targets: image-local
        env:
          DEFAULT_TAG: ${{ env.BUILD_TAG }}
          DOCKERFILE: ${{ matrix.docker_file }}
      -
        name: Start
        run: |
          docker compose up -d
        working-directory: test/${{ matrix.dir }}
        env:
          NEXTCLOUD_IMAGE: ${{ env.BUILD_TAG }}
          NEXTCLOUD_CONTAINER: ${{ env.CONTAINER_NAME }}
      -
        name: Check container logs
        uses: crazy-max/.github/.github/actions/container-logs-check@bb328ea508cd6a89d0865555ddbeb148e5724aed # v1.3.0
        with:
          container_name: ${{ env.CONTAINER_NAME }}
          log_check: "ready to handle connections"
      -
        name: Logs
        if: always()
        run: |
          docker compose logs
        working-directory: test/${{ matrix.dir }}
        env:
          NEXTCLOUD_IMAGE: ${{ env.BUILD_TAG }}
          NEXTCLOUD_CONTAINER: ${{ env.CONTAINER_NAME }}
